export const ENDPOINT = {
	GET_MOVIE_GENRES: "/genre/movie/list",
	GET_TV_GENRES: "/genre/tv/list",
	GET_REQUEST_TOKEN: "/authentication/token/new",
	GET_TRENDING_MOVIES: "/movie/popular",
	GET_LATEST_MOVIES: "/discover/movie",
	GET_POPULAR_MOVIES_THIS_WEEK: "/trending/movie/week",
	GET_FEATURED: "/movie/top_rated",
	GET_VIDEO: "/movie/:movie_id/videos",
	GET_UPCOMING_MOVIES: "/movie/upcoming",
	GET_TV_SERIES: "/discover/tv",
	GET_VIDEO_DETAILS: "/movie/:movie_id",
	GET_MOVIE_CREDITS: "/movie/:movie_id/credits",
	GET_RECOMMENDED_MOVIE: "/movie/:movie_id/recommendations",
	GET_MOVIE_REVIEWS: "/movie/:movie_id/reviews",
	GET_TV_DETAILS: "/tv/:movie_id",
	GET_TV_CREDITS: "/tv/:movie_id/credits",
	GET_RECOMMENDED_TV: "/tv/:movie_id/recommendations",
	GET_TV_REVIEWS: "/tv/:movie_id/reviews",
	GET_MOVIE_VIDEO: "/movie/:id/videos",
	GET_TV_VIDEO: "/tv/:id/tv",
};
